version: "3.13.2"

services:
  db:
    image: postgres:16
    container_name: db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  etl:
    build: .
    container_name: etl_container
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
    volumes:
      - ./data:/app/data
    command: python etl/run_pipeline.py
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:

# pour executer :
# docher-compose up --build