name: Run ETL pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-etl:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL pipeline
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sales_db
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          python etl/run_pipeline.py
